// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDoyt4Yd8M8dAkOd5RvrUYXV2QNYy1rw',
    appId: '1:283942785831:web:795bb4211fc5d6037ccf02',
    messagingSenderId: '283942785831',
    projectId: 'delvoo-87f61',
    authDomain: 'delvoo-87f61.firebaseapp.com',
    storageBucket: 'delvoo-87f61.appspot.com',
    measurementId: 'G-S938G0YHXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4bwDnyM-4MZCyKECmYe95UXQElBgsG8',
    appId: '1:283942785831:android:dfabdf40cc69f0037ccf02',
    messagingSenderId: '283942785831',
    projectId: 'delvoo-87f61',
    storageBucket: 'delvoo-87f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYhf3_7Xm2G5yv-759iF0kBfr2T5yvWI',
    appId: '1:283942785831:ios:c961ac48f7b545d67ccf02',
    messagingSenderId: '283942785831',
    projectId: 'delvoo-87f61',
    storageBucket: 'delvoo-87f61.appspot.com',
    iosClientId: '283942785831-taodtkvj9arbrp6ruib5bkqob54rtac6.apps.googleusercontent.com',
    iosBundleId: 'com.example.delvoodelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYhf3_7Xm2G5yv-759iF0kBfr2T5yvWI',
    appId: '1:283942785831:ios:c961ac48f7b545d67ccf02',
    messagingSenderId: '283942785831',
    projectId: 'delvoo-87f61',
    storageBucket: 'delvoo-87f61.appspot.com',
    iosClientId: '283942785831-taodtkvj9arbrp6ruib5bkqob54rtac6.apps.googleusercontent.com',
    iosBundleId: 'com.example.delvoodelivery',
  );
}
